name: terraform-cd-stg
on:
  push:
    branches:
      - staging
    paths:
      - 'infra/environment/stg/**.tf'
      - '.github/workflows/**-stg.yaml'

permissions:
  contents: 'write'
  id-token: 'write'

jobs:
  terraform-cd-stg:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra/environment/stg
    steps:
      # https://github.com/actions/checkout#Checkout-a-different-branch
      - id: 'checkout'
        name: checkout staging branch
        uses: 'actions/checkout@v3'
        with:
          ref: staging
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0' # https://github.com/google-github-actions/auth
        with:
          create_credentials_file: 'true'
          workload_identity_provider: ${{ secrets.workload_identity_provider }}
          service_account: ${{ secrets.service_account }}
          access_token_lifetime: 1200s
      
      - id: 'setup'
        name: 'set up for terraform command'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.3

      - id: 'gcloud-auth-login'
        name: gcloud auth login by workload identity
        run: |-
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
      
      - id: 'td-fmt'
        name: 'Run terraform fmt'
        run: terraform fmt --recursive
        continue-on-error: true

      - id: 'tf-init'
        name: 'Run terraform init'
        run: terraform init

      - id: 'tf-validate'
        name: 'Run terraform validate'
        run: terraform validate -no-color
        continue-on-error: false

      - id: 'setup-tfcmt'
        name: Install tfcmt
        run: |
          sudo curl -fL -o tfcmt.tar.gz https://github.com/suzuki-shunsuke/tfcmt/releases/download/$TERRAFORM_VERSION/tfcmt_linux_amd64.tar.gz
          sudo tar -C /usr/bin -xzf ./tfcmt.tar.gz
        env:
          TERRAFORM_VERSION: "v3.2.1"

      - id: 'tfcmt'
        name: Terraform apply
        run: |
          if [ -n "$PR_HEAD_SHA" ]; then
            export GITHUB_SHA=$PR_HEAD_SHA
          fi
          tfcmt apply -- terraform apply -auto-approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          PR_NUMBER: ${{ github.event.number }}